### ISSUE TITLE
The order of batches

### ISSUE THREAD

**Issue by phoebee-h** [NikolayOskolkov/HowToBatchCorrectSingleCell#1]
Hi,
Thanks for sharing, which is really helpful!
When you plot this figure, if I understand it correctly, you are making the linear correlation between each PCs and each batches (how each adj.R^2 comes from).

![image](https://user-images.githubusercontent.com/28743573/67540233-3eb70100-f717-11e9-92cb-0fd24088921b.png)

I'd like to ask is, if I have 3 samples from different lanes, we could plot this at first, and try to find a linear regression, right? But, as shown in this plot, I think the order of samples could affect the regression line. What do you think about this problem? How would you deal with this?

![image](https://user-images.githubusercontent.com/28743573/67540837-8179d880-f719-11e9-8cae-aa91b0334e9c.png)

P.S. The data is from [GSE77288](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE77288). To make my question simple, I only discuss the sample difference at first.

**Comment by NikolayOskolkov** [comment]
Hi Phoebe,

you are asking a very good statistical question, many people get confused by the order of levels of categorical variables. First, a batch is a categorical variable, on your plot there are three levels. This is exactly why you should model a batch variable as a factor (in R) and not a numeric. In Machine Learning terminology, the factor data type is called one-hot-encoding. In mathematical statistics a factor data type is called "dummy variables". Those three names refer to the same thing: instead of having one vector with batch codes (e.g. 0, 1, 2) we build three vectors, or you can say a matrix (one element for each sample) where 1 means "the sample belongs to this batch" and 0 means "does not belong", so each sample belongs to only one batch, therefore there will be only one 1 in each "row" of the matrix. In your example plot, indeed, unless a batch has some additivity meaning (like time, e.g. 0 means the earliest, 1 means later, 2 means the latest) the slope of the regression will depend on the order of the batches, because from the point of view of a machine, 1>0 and 2>1. This is exactly why categorical variables should not be coded as 0, 1, 2 but rather as "factor", "dummy" or "one-hot-encoded"

**Comment by phoebee-h** [comment]
Hi Nikolay,
Thanks for the prompt reply! What you were saying is very clear, and I will be cautious when analyzing categorical data. To whom may also have the same problem like me, check this out:
https://stats.idre.ucla.edu/r/modules/coding-for-categorical-variables-in-regression-models/
